# Generated by Django 5.2 on 2025-05-08 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_follow_userprofile_followers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='profile_pocture',
            new_name='profile_picture',
        ),
    ]
